name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build MetalANGLEKit
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Check
        run: find /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/
      - name: Setup repository
        run: |
          brew install ninja
          ./setup-angle.sh
      - name: Build angle
        run: |
          ./build-angle.sh Release
      - name: Build MetalANGLEKit
        run: |
          ./build-metalanglekit.sh
      - name: Archive MetalANGLEKit      
        uses: actions/upload-artifact@v4
        with:
          name: metalanglekit
          path: |
            build/
            
